with open(input("Type your name: ") +".txt", "w") as f:
    f.write(input("Type the name of an animal: ") +"\n")
    f.write(input("Type another name: ") +"\n")
    f.write(input("Type a verb ending with ing: ") +"\n")
    f.write(input("Type an adjective: ") +"\n")
    f.write(input("Type the name of an animal: ") +"\n")
    f.write(input("Type an emotion: ") +"\n")
    f.write(input("Type a verb ending with ing: ") +"\n")
    f.write(input("Type an adjective that ends with ist or est: ") +"\n")
    f.write(input("Type the name of a restaurant: ") +"\n")
    f.write(input("Type a type of food: ") +"\n")
    f.write(input("Type a street name: ") +"\n")
    f.write(input("Type a body part: ") +"\n")
    f.write(input("Type an adjective: ") +"\n")
    f.write(input("Type an verb ending with ed: ") +"\n")
